### ISSUE TITLE
ecto_enum 1.1 not yet released to Hex

### ISSUE THREAD

**Issue by josephan** [gjaldon/ecto_enum#51]
For now I am doing:
```
{:ecto_enum, github: "gjaldon/ecto_enum"}
```
Thank you for creating ecto enum. It's very handy.

**Comment by gjaldon** [comment]
@josephan sorry for the delay! I just published EctoEnum 1.1 to Hex and loosened dep requirements so this will no longer be a problem in the future.

**Comment by Anber** [comment]
You still have a wrong published version.
Actually, there is a problem with tags. https://github.com/gjaldon/ecto_enum/blob/v1.1.0/lib/ecto_enum/postgres.ex looks really outdated.

**Comment by gjaldon** [comment]
Haven't published master yet but 1.1 is already published https://hex.pm/packages/ecto_enum.
